[package]
name = "advent_code_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
peeking_take_while = "1.0.0"
id_tree = "1.8.0"
regex = "1.8.1"
point-index = "0.1.2"